server:
  port: 8081

spring:
  application:
    name: cache-gateway
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

services:
  dbfetcher:
    url: http://localhost:8082
