server:
  port: 8081

spring:
  application-name: cache-gateway
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cache-gateway
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

cache:
  policies:
    default:
      ttl: 60
      consistency: ASIDE
    tenant42:
      ttl: 120
      consistency: READ_THROUGH

services:
  dbfetcher:
    url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,beans,env
