server:
  port: 8082

spring:
  application-name: db-fetcher
  datasource:
    url: jdbc:postgresql://localhost:5432/rediserve
    username: rediserve
    password: rediserve
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: PostgreSQLDialect

services:
  cachegateway:
    url: http://localhost:8081