server:
  port: 8083

spring:
  application-name: orchestrator

services:
  cachegateway:
    url: http://localhost:8081

cache:
  policies:
    default:
      ttl: 60
      consistency: ASIDE
    tenant42:
      ttl: 110
      consistency: READ_THROUGH

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,beans,env
